# Generated by Django 4.1.6 on 2023-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='elevator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('state', models.CharField(choices=[('UNDER_MAINTENANCE', 'UNDER_MAINTENANCE'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DEPRECATED', 'DEPRECATED')], default='ACTIVE', max_length=100)),
                ('current_floor', models.PositiveIntegerField(default=0, null=True)),
                ('destination_floor', models.PositiveIntegerField(null=True)),
                ('door_status', models.CharField(default='CLOSED', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
