# Generated by Django 4.1.6 on 2023-02-05 22:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_alter_elevator_options_elevator_is_moving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='user_requests',
            field=models.CharField(default=[], max_length=10000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
